site_name: PetCare Agendamento - Documentação Técnica
site_url: https://jackssondev.github.io/agendamento/
site_description: Documentação de arquitetura, segurança e desenvolvimento para a aplicação PetCare.
repo_url: https://github.com/JackssonDev/agendamento

# ----------------------------------------------------
# 1. Configuração do Tema (Material for MkDocs)
# ----------------------------------------------------
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
  features:
    - navigation.tabs
    - content.code.annotate
    - toc.follow
    - content.tabs

# ----------------------------------------------------
# 2. Plugins e Extensões
# ----------------------------------------------------
plugins:
  - search
  - mermaid2 # Garante que o JavaScript para diagramas seja injetado

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.extra

# ----------------------------------------------------
# 3. Estrutura de Navegação (Nav)
# ----------------------------------------------------
nav:
  - Home: index.md
  - Introdução: index.md
  - Setup e Instalação: setup.md
  - Arquitetura:
      - Visão Geral: architecture.md
      - APIs e Endpoints: architecture.md#endpoints-e-potencial-de-api
  - Modelagem do Sistema:
      - Modelos de Dados (ERD): architecture.md#modelos-de-dados-erd-simplificado
      - Fluxos Críticos: architecture.md#fluxos-criticos-do-sistema
  - Qualidade e Padrões: guidelines.md
  - Segurança: security.md