# Generated by Django 5.2.6 on 2025-09-18 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pet')),
                ('tipo', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('roedor', 'Roedor'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('raca', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade (anos)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['nome'],
            },
        ),
    ]
