# Generated by Django 5.2.6 on 2025-09-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_servico_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='servico',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cidade',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='estado',
            field=models.CharField(default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('transferencia', 'Transferência Bancária')], default='dinheiro', max_length=20, verbose_name='Forma de Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(to='agendamentos.servico', verbose_name='Serviços'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Total'),
        ),
    ]
