# Generated by Django 5.2.6 on 2025-09-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_remove_agendamento_servico_agendamento_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, verbose_name='Motivo do Cancelamento'),
        ),
    ]
