# Generated by Django 5.2.6 on 2025-09-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_agendamento_motivo_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='icone',
            field=models.CharField(default='fas fa-paw', help_text='Ex: fas fa-dog, fas fa-cat, fas fa-syringe', max_length=50, verbose_name='Ícone (classe do FontAwesome)'),
        ),
    ]
