# Generated by Django 5.2.6 on 2025-09-27 11:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_servico_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data', 'horario_inicio'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='horario',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='duracao_total_minutos',
            field=models.PositiveIntegerField(default=30, verbose_name='Duração Total (minutos)'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_inicio',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Horário de Início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=30, help_text='O tempo em minutos que este serviço leva para ser concluído.', validators=[django.core.validators.MinValueValidator(15)], verbose_name='Duração (minutos)'),
        ),
    ]
