# Generated by Django 5.2.6 on 2025-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_agendamento_options_remove_agendamento_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos_imagens/'),
        ),
    ]
